WeCrab/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WeCrab.Models;

namespace WeCrab.Controllers
{
    public class CategoryController : Controller
    {
        private ApplicationDbContext _context;

        public CategoryController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET: Category
        public ActionResult Index()
        {
            var categoryModel = _context.Category.ToList();

            return View(categoryModel);
        }


        public ActionResult Details(int i)
        {
            var categoryId = _context.Category.SingleOrDefault(element => element.Id == i);
            return View(categoryId);
        }
    }
}

WeCrab/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WeCrab.Models;
using WeCrab.ViewModel;

namespace WeCrab.Controllers
{
    public class MovieController : Controller
    {
        public ActionResult Index()
        {
            var movieModel = getMovies();

            return View(movieModel);
        }

        private IEnumerable<Movie> getMovies()
        {
            var movies = new List<Movie>
            {
                new Movie {Id = 1, Name = "Totally Spies"},
                new Movie {Id = 2, Name = "Ben 10 Ultimate Alien"}
            };


            return movies;
        }

        public ActionResult Details(int mId)
        {
            var movieId = getMovies().SingleOrDefault(m => m.Id == mId);

            return View(movieId);
        }

        // GET: Movies/Random
        /*public ActionResult Random()
        {
            var movie = new Movie() { Name = "Life with Louie" };

            var categories = new List<Category>
            {
                new Category {Name = "Heniek"},
                new Category {Name = "Barbara"}
            };

            var randomViewModel = new MovieViewModel
            {
                Categories = categories,
                Movie = movie
            };

            return View(randomViewModel);
        }*/


        // W RouteConfig ustawiliśmy jakąś generyczną ścieżke a tutaj ją określamy, ważne jest aby podać dobry adres oraz parametry wraz z ograniczeniami 
        //regex oznacza że określamy ile znaków maksymalnie może przechowywać parametr a po przecinku range określa zakres
        [Route("movies/released/{year}/{month:regex(\\d{2}):range(1, 12)}")]
        public ActionResult ByReleaseDate(int year, int month)
        {
            return Content(year + " " + month);
        }

        /*//GET: Movies/Edit/parameter
        public ActionResult Edit(int id)
        {
            return Content("ID " + id);
        }

        //GET: Movies/Index?parameter&parameter
        public ActionResult Index(int? pageIndex, string sortBy)
        {
            if (!pageIndex.HasValue)
            {
                pageIndex = 1;
            }

            if (String.IsNullOrWhiteSpace(sortBy))
            {
                sortBy = "Name";
            }

            return Content("Page index: " + pageIndex + " " + sortBy);
        }*/
    }
}

WeCrab/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Web Crab</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
@Html.Partial("_Navbar")
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - Web Crab App</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>

WeCrab/Views/Shared/_Navbar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Web Crab", "Index", "Home", new {area = ""}, new {@class = "navbar-brand"})
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Filmy", "Index", "Movie")</li>
                <li>@Html.ActionLink("Kategorie", "Index", "Category")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>